VisionPipeline:
  keywords:
    - class_name
    - score
    - obb_corners
    - obb_center
    - obb_rot_quat
    - tracking_id
    - tracking_score
  object_color_dict: 
    - {hca_front : [1.0, 0.0, 0.0, 0.5],
       hca_back : [0.7, 0.0, 0.0, 0.5],
       side1 : [0.5, 0.0, 0.0, 0.5],
       side2 : [0.2, 0.0, 0.0, 0.5],
       battery : [0.0, 1.0, 0.0, 1.0],
       plastic_clip : [0.0, 1.0, 0.0, 1.0],
       pcb_covered : [0.0, 1.0, 0.0, 1.0],
       pcb : [0.0, 0.0, 1.0, 1.0],
       internals : [0.5, 0.0, 0.5, 1.0]}
  
